### ISSUE TITLE
Feature Proposal: Advanced/Dedicated Warehouse Modes

### ISSUE THREAD

**Issue by TheDogKSP** [TheDogKSP/MoreEffectiveTransfer#4]
**Feature overview:**
- per individual Warehouse, have a toggle/switch to set the warehouse into one of the following operating modes:
   * NORMAL: warehouse behaves as in vanilla (default setting)
   * LOCAL ONLY: warehouse will only serve local supply/demand and will never import/export on its own
   * I/E ONLY: warehouse will only IMPORT/EXPORT, as well as perform inter-warehouse transfer with other warehouses set to NORMAL or LOCAL ONYL ("forwarding"). It will never serve local supply/demand.

**Required functionalities:**
- functionality can be globally switched on/off in mod options
- functionality does not depend on existing settings (warehouse first, reserve trucks), and is not mutually exclusive with any setting, but complements them
- per warehouse setting on warehouse ui (switch/button/...)
- per warehouse setting needs to be persisted into save file

**Boundaries and Out of Scope:**
- this functionality, when enabled, will not prevent any non-warehouse producer and consumer building in the city to perform direct transfers between each other, if that is the closest distance match
- this functionality, when enabled, will not prevent any non-warehouse producer and consumer to perform their own imports/exports, if that is the result of the offer match-making

**Details of operation**
...

**Comment by AdmiralElectron** [comment]
### The issue that needs to be addressed:

Warehouse modes allow/disallow inter warehouse transfers and import/export in same conditions. This means if a warehouse has excess, it will look to buy locally from other warehouses and if it can not find anyone locally, it'll immediately import. Similarly, warehouses will look to sell locally and immediately export if they can not find a local buyer warehouse.

Because excess supply and excess demand at different warehouses are not happening at the same time, you will see unnecessary imports and exports. 

Custom warehouse modes or local and import/export modes of warehouses are intended to fix this issue by preventing import/export at some warehouses and reserving some warehouses for import/export only.  However, it is a major rework and might as well be a different mod.

### Custom balanced modes as a solution:

In vanilla balanced mode, the warehouse will start buying from other warehouses and importing as soon as the inventory level falls below 50%. In the new balanced mode, they will only import between 0% to 25% inventory levels. Similarly, they will only export if the inventory level exceeds 90% inventory instead of exporting above 75% inventory.

### Required functionality

- Changes to balanced mode (Import happens between 0% to 25% instead of 0% to 50%, export happens between 90% to 100% instead of 75% to 100%)
- Functionality in-game options to enable/disable this new balanced mode globally, only this preference needs to be saved.
- No requirement to configure each warehouse individually.
- Other settings are unaffected.

### Possible scope

- Fill mode only imports between 0% to 50% instead of 0% to 100%
- Empty mode only exports between 50% to 100% instead of 0% to 100%.

Note: exact numbers are subject to change based on in-game testing.

**Comment by TheDogKSP** [comment]
![image](https://user-images.githubusercontent.com/12222030/153730611-fcbe3cbc-ec8b-4fef-9c34-15318f783ff2.png)

**Comment by TheDogKSP** [comment]
Implementation possibility 1: 
- replace current warehouse ai (method: ProduceGoods), send out incoming/outgoing offers with desired priority according to new table above

Implementation possibility 2:
- in transfer manager offer matching: query warehouse fill status and operating mode, do not match with outsideconnection ai offers when conditions not fulfillled

Assessment:
- option 1 (warehouse ai): additional harmony method patching, increased chance for mod incompatibilities
- option 2 (offer matching): performance penalty for additional warehouse queries

**Comment by TheDogKSP** [comment]
I have doubts about these new modes, and I doubt they will work fine.
1. Empty mode: the observed effect will be that all the valuable unique factory goods sit in a warehouse and dont get exported. Not desirable.
2. Balanced mode: I guess it will break supply chains if transfer to other warehouses only happen at 75%+ fill level. Observed effect will be that a "distribution warehouse" close to the commercial zone will sit at very low stock, while an "import warehouse" at the city entrance sits on 50%+ stock, but nothing gets transferred.

**Comment by AdmiralElectron** [comment]
I do not see any problems in the new modes. I am assuming you are not talking about local and import/export modes, but the new balanced, fill and empty modes I proposed. Let me explain what I expect to happen.

1.  In the new empty mode(supposed unique factory goods), there will be 3 input/outputs between 0% to 50%. 

- First will be unique factories selling the goods to the warehouse, this is the only input.
- Second will be local commercial places which will buy those goods.
- Third will be other warehouses buying goods from you. These warehouses will be the ones which are placed in commercial centers away from any unique factory and looking to sell the goods to nearby stores. They will be placed in fill mode. 

So, you are still selling the goods, you're just preferring to sell it locally which will help to avoid unnecessary importing.

If you still making more unique factory goods than local demand can handle, then you will cross the 50% inventory and start exporting beyond that. The 50% in reserve is not an issue because some buffer stock is going to be present even in commercial zone warehouses which would be set to fill. 

2. I'm a little confused about which goods you are talking about because we only sell unique factory goods in commercial zones, which you are calling 'distribution center'. But, we can not import them, so there won't be an 'import warehouse' for them. In fact, in thenew mode I am proposing, there won't be any dedicated local or import/export warehouses. So, if someone is sitting at very low stock(<25%), they will import and they won't run out of material. We can change the limit to 30% if needed. They would already be trying to buy from other warehouses if they are under (<50%). Transfer to other warehouses only happens at 75% even in vanilla balanced mode. 

We are not touching any local supply chain logic, we are only delaying import and export, which is expected to avoid unnecessary import/export that would have happened because of asynchronous incoming/outgoing offers.

Let me put a picture.

**Comment by AdmiralElectron** [comment]
This is vanilla

![image](https://user-images.githubusercontent.com/68630007/153761874-ce7bfdf4-22d0-48fe-8a25-36becff6ae33.png)


This is proposed

![image](https://user-images.githubusercontent.com/68630007/153761896-3e36e668-8b81-430d-b722-885bd033100b.png)

**Comment by TheDogKSP** [comment]
Regarding "new fill & empty" modes: 
- I disagree with the premise that exports should be avoided as much as possible, always prefering local demand. Especially for unique factory products, which are high value, I do not want them to be consumed locally. I want them to be exported immediately as this is a major stream of revenue. Right now that can be achieved by having a warehouse set to empty right next to the unique factory district.

Regarding new balanced mode:
- looks reasonable, I guess we'll try & test this one

**Comment by AdmiralElectron** [comment]
Regarding new fill and empty modes:

Selling local and exporting does not have a sales price difference, so the revenue amount is not going to differ.
The revenue realization happens when the truck reaches the destination. So, local demand would be served faster than export.
The expected effect is just lowered traffic and congestion at cargo facilities. 
 
(I recall that in earlier versions of industries DLC, profit was going to cargo stations/ports if they were used for exporting. As such industries tab showed a lot of losses, I do not know how they fixed this issue. We can test whether profit realization happens when the truck reaches the cargo station or the cargo train despawns at the edge of the map, I am suspecting later.)

If there is enough local demand, revenue amount or revenue time lag is unaffected between vanilla mode and the proposed mode. There won't be any buffer stock.

If there is not enough local demand, you should see around 50% buffer stock sitting in the warehouse perpetually, and just that fixed amount will have no revenue realization. This would be a one-time event. From then on, the ongoing revenue stream would be unaffected in terms of the amount of money and time lag between the goods being delivered to the warehouse and goods being delivered to the final customer.

This buffer stock always sitting in the warehouse is expected every time you use the warehouse in fill or balanced mode and the one time cost of acquiring the buffer stock is accepted because it allows the buildings which require these goods to get them as soon as possible. (I prefer local delivery because excessive imports release hoards of donut vans from cargo facilities, which can trigger a traffic slowdown, requiring time to clear it.)

Ultimately, it's intended to be managerial discretion to use the new fill and empty mode, and they can be separate options compared to the new balanced mode if needed. But, there are no functional problems in these modes that make them unusable in any situation and I personally see them as a good thing because it reduces traffic.

**Comment by TheDogKSP** [comment]
_"Selling local and exporting does not have a sales price difference, so the revenue amount is not going to differ."_

Is that really so?
That would mean that the very last paragraph here would be wrong:
https://skylines.paradoxwikis.com/Supply_chain
_"Materials transported from building to building do not earn you any money. Only materials shipped from the city bring revenue."_

**Comment by AdmiralElectron** [comment]
The Wiki is clearly outdated, even the sentence written above the point you quoted is outdated, I just mentioned that in my comment above. When industries DLC came out, all the profit from mass transit export was going to the cargo buildings, so industries tab would show losses. They fixed this, but even now warehouses still claim credit for all the profits from the goods they sell.

Building to building transfers are indeed free, but only if both of them are player owned. 

So, it would go something like..

Outside >(Expense)> raw material storing warehouse >(Free)> Processor >(Free)> Processed Material warehouse >(Free)> Unique factory>(Free)>Unique factory goods warehouse>(Revenue)>zoned commercial. 

Even now, the industries district tab shows wrong accounting info if all the materials are being used by unique factories.

**Comment by AdmiralElectron** [comment]
From my guide to industries..
![image](https://user-images.githubusercontent.com/68630007/153838373-c4ec18a6-1dc5-4021-a409-d1b6fd632537.png)

**Comment by TheDogKSP** [comment]
interesting, where can I find your guide online?

**Comment by AdmiralElectron** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=2643985670

**Comment by TheDogKSP** [comment]
release [2.0.5.220220]
